### ISSUE TITLE
eigen

### ISSUE THREAD

**Issue by kasra0** [D-BookeR/Traitement_d_images_et_de_videos_avec_OpenCV3#2]
Bonjour,

il semblerait que le repo eigen donné dans le livre ne soit plus bon .

"Cloning into 'eigen'...
remote: Repository not found.
fatal: repository 'https://github.com/RLovelett/eigen.git/' not found"

Cdt,

**Comment by kasra0** [comment]
J'ai personnellement cloné ce dépôt https://github.com/eigenteam/eigen-git-mirror

**Comment by LaurentBerger** [comment]
Merci
je vais actualiser les scripts. La modification est [récente](http://eigen.tuxfamily.org/index.php?title=News:Eigen_now_offers_a_git_mirror_on_github!)
